'use strict'
export default {
    APP_INIT:'APP_INIT',
    APP_NAVIGATE:'APP_NAVIGATE',
    APP_NAVIGATE_GOBACK:'APP_NAVIGATE_GOBACK',
    APP_RESET_NAVIGATOR:'APP_RESET_NAVIGATOR',

    WORD_GET_BOOKS:'WORD_GET_BOOKS',
    WORD_GET_SECTIONS:'WORD_GET_SECTIONS',
    WORD_GET_WORDS:'WORD_GET_WORDS'
}
