'use strict'
export default {
    APP_INIT:'APP_INIT',
    APP_NAVIGATE:'APP_NAVIGATE',
    APP_NAVIGATE_GOBACK:'APP_NAVIGATE_GOBACK',
    APP_RESET_NAVIGATOR:'APP_RESET_NAVIGATOR',

    APP_UPDATE_HEADER:'APP_UPDATE_HEADER',
    TOAST:'TOAST',
    ALERT:'ALERT',
    POPUP:'POPUP',
    SET_THEME:'SET_THEME',
    SET_WORD_PAGE_THEME:'SET_WORD_PAGE_THEME',
    

    WORD_GET_BOOKS:'WORD_GET_BOOKS',
    WORD_GET_CLASSIFY:'WORD_GET_CLASSIFY',
    WORD_GET_SECTIONS:'WORD_GET_SECTIONS',
    WORD_GET_WORDS:'WORD_GET_WORDS',
    WORD_GET_MEANING:'WORD_GET_MEANING',

    SEARCH_BOOK:'SEARCH_BOOK',

    USER_ADD_BOOKS:'USER_ADD_BOOKS',
    USER_REMOVE_BOOKS:'USER_REMOVE_BOOKS',
    USER_GET_BOOKS:'USER_GET_BOOKS',
    USER_MARK_WORD:'USER_MARK_WORD',
    USER_GET_CUSTOMIZED_BOOKS:'USER_GET_CUSTOMIZED_BOOKS'
}
